[package]
name = "rumpunch"
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"

readme = "README.md"
description = "UDP multi-hole puncher for NAT traversal (including, sometimes, Symmetric NATs)"
repository = "https://github.com/neil2468/rumpunch.git"

keywords = ["nat-traversal", "udp", "hole-punching", "symmetric-nat", "nat"]
categories = ["network-programming"]

[dependencies]
anyhow = "1.0.72"
postcard = { version = "1.0.4", features = ["alloc"] }
rand = "0.8.5"
serde = { version = "1.0.164", features = ["derive"] }
thiserror = "1.0.43"

[[example]]
name = "foo"
